---
editor_options: 
  markdown: 
    wrap: sentence
---

## Column 1 {data-width="450"}

### The PAP App

Ever wondered what you should put in your pre-analysis plan (PAP)?
We are here to help!
The PAP App will guide you through the process by asking you a number of questions about your study.
It will then produce a draft PAP.
This PAP is valid, optimal, and derived from first principles.
This is a **beta version** of the app, and for the time being the results should be used with caution!

### General procedure

The general procedure is as follows: You specify a null hypothesis, and test size.
You furthermore specify a prior over the parameter, and probabilities for each of the components to be available.
The tests produced by this app control size under the null, and maximize expected power.

The app produces a test for the full data, when all components are available.
When not all components are available, worst-case assumptions need to be made about the unavailable ones, and the resulting test decision must be reported.
This procedure results in the test with the highest expected power that is incentive compatible and controls size.
For more details see our workingpaper "Optimal Pre-Analysis Plans: Statistical Decisions Subject to Implementability" ([optimal_preanalysis_plans.pdf](https://maxkasy.github.io/home/files/papers/optimal_preanalysis_plans.pdf)), as well as the presentation slides ([implementable_preanalysis_slides_kasy.pdf](https://maxkasy.github.io/home/files/slides/implementable_preanalysis_slides_kasy.pdf)).



## Column 2 {data-width="550"}

### Linear program

For optimal PAPs, the app solves the following linear programming problem: \begin{align*}
  \max_{b, t} \sum_{X_J, J} b(X_J,J) \cdot  P_\pi(X_J,J) & & & &\text{(Expected power)}\\
  \text{s.t.}\quad
  \sum_{X}  t(X)  \cdot P_{\theta_0}(X) &\leq \alpha, &&&\text{(Size control)}\\
  b(X_J,J), t(X) &\in [0,1] & \forall\; J,X,&&\text{(Support)}\\
  b(X_J,J) &\leq t(X) & \forall\; J,X.&&\text{(Monotonicity)}
\end{align*}

The app returns the solution for $t$.
The test that should then be implemented is given by $$b(X_J,J) = \min_{X';\;X'_J=X_J} t(X').$$

### Four cases

The current version of the app allows for the following *four cases*:

1.  Binary outcomes, optimal PAP\
2.  Binary outcomes, simple cutoff rule\
3.  Normal outcomes, optimal PAP\
4.  Normal outcomes, simple cutoff rule
